### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by afaur** [eface2face/jquery-meteor-blaze#3]
I was wondering what your build process was like on this as was want to build the files in the dist directory myself without including some of the meteor-client modules/libraries.

I would like use:
*Meteor
*Meteor.Tracker
*Meteor.ReactiveVar
*Meteor.Blaze
*Meteor.BlazeTools
*Meteor.Templating
*Meteor.Spacebars
*Meteor.SpacebarsCompiler

But not include:
Meteor.Base64
Meteor.EJSON
Meteor.Random
Meteor.IdMap
Meteor.OrderedDict
Meteor.ObserveSequence
Meteor.HTMLJS
Meteor.HMLTools

Any chance you could document this or explain it in a way that I could go about making a PR against the readme to include this for anyone else?

**Comment by afaur** [comment]
I think I was able to figure this out...

`browserify jquery-meteor-blaze.js -o ./dist/jquery-meteor-blaze.devel.js`

Let me know if this looks correct.

**Comment by afaur** [comment]
I have opened a PR that adds a build script to the project: https://github.com/eface2face/jquery-meteor-blaze/pull/4

Let me know if you want me to alter this in any way or use gulp or some other tool to handle the min and gzip version as that is not supported with this PR.

**Comment by murillo128** [comment]
hi afaur!

Regarding the meteor packages, I had to include them because of meteor dependencies. The meteor client module which load all the submodules is in here:

https://github.com/eface2face/meteor-client

And each of the modules are a 1-to-1 clone from the meteor ones using this generator.
https://github.com/eface2face/meteor-module-generator

I still have pending upgrading current code to meteor 1.2 and see if I can remove any of the dependencies.

Regarding the script, yes, it is just a browserify, it would be great to have a gulp script for generating all the dist files.
